// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/DashboardTwoTone';
import ShopTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/ShopTwoTone';
import CrownOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import ReconciliationOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/ReconciliationOutlined';
import AppstoreTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/AppstoreTwoTone';
import SmileOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import SolutionOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/SolutionOutlined';
import HomeTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/HomeTwoTone';
import ShoppingCartOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/ShoppingCartOutlined';
import UnorderedListOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/UnorderedListOutlined';
import PlusOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/PlusOutlined';
import MinusSquareTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/MinusSquareTwoTone';
import HddTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/HddTwoTone';
import GroupOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/GroupOutlined';
import ReconciliationTwoTone from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/ReconciliationTwoTone';
import UserOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TableOutlined from 'C:/Users/Acer/Desktop/JAVA PROJECTS/pasal/src/main/client/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { DashboardTwoTone, ShopTwoTone, CrownOutlined, ReconciliationOutlined, AppstoreTwoTone, SmileOutlined, SolutionOutlined, HomeTwoTone, ShoppingCartOutlined, UnorderedListOutlined, PlusOutlined, MinusSquareTwoTone, HddTwoTone, GroupOutlined, ReconciliationTwoTone, UserOutlined, TableOutlined };
